// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE37-MJuyzvSgUMGu8sUuVKofBs5REXk8',
    appId: '1:1069347566143:web:c0f2b5c5f343560483fe8a',
    messagingSenderId: '1069347566143',
    projectId: 'krishiurja-3320',
    authDomain: 'krishiurja-3320.firebaseapp.com',
    storageBucket: 'krishiurja-3320.appspot.com',
    measurementId: 'G-RTBY01GHNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDi3ISML9uI5rO3UqKhmENn3muJBU5qME',
    appId: '1:1069347566143:android:30404297cb63a40583fe8a',
    messagingSenderId: '1069347566143',
    projectId: 'krishiurja-3320',
    storageBucket: 'krishiurja-3320.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2QJ_bMjx-ax2ukM3TjQCeg_gHilQAqb4',
    appId: '1:1069347566143:ios:fbc85a43a714a80183fe8a',
    messagingSenderId: '1069347566143',
    projectId: 'krishiurja-3320',
    storageBucket: 'krishiurja-3320.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2QJ_bMjx-ax2ukM3TjQCeg_gHilQAqb4',
    appId: '1:1069347566143:ios:fbc85a43a714a80183fe8a',
    messagingSenderId: '1069347566143',
    projectId: 'krishiurja-3320',
    storageBucket: 'krishiurja-3320.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
